common_params:
  boosting: gbdt
  data_sample_strategy: bagging
  bagging_fraction: 0.75
  bagging_freq: 1
  bagging_by_query: true
  num_iterations: 1000
  learning_rate: 0.06
  num_leaves: 127
  max_depth: 10
  min_data_in_leaf: 10
  feature_fraction: 0.75
  early_stopping_round: 100
  use_missing: true
  num_threads: 6

params_bin:
  objective: binary
  metric: binary_logloss
  is_unbalance: false
  scale_pos_weight: 1.0

params_rank:
  objective: lambdarank
  metric: ndcg
  lambdarank_truncation_level: 8
  eval_at: [1,2,3,4,5]

params_reg:
  objective: regression
  metric: rmse
