# CatBoost parameters with common_params
common_params:
  iterations: 1000
  learning_rate: 0.03
  depth: 6
  random_seed: 42
  use_best_model: true
  verbose: 50
  early_stopping_rounds: 100
  thread_count: 6

params_bin:
  objective: Logloss
  eval_metric: AUC

params_rank:
  objective: YetiRank
  eval_metric: NDCG

params_reg:
  objective: RMSE
  eval_metric: RMSE
