common_params:
  boosting: gbdt
  data_sample_strategy: bagging
  bagging_fraction: 1.0
  bagging_freq: 1
  bagging_by_query: true
  num_iterations: 1000
  learning_rate: 0.1
  num_leaves: 127
  max_depth: -1
  min_data_in_leaf: 10
  feature_fraction: 1.0
  early_stopping_round: 100
  use_missing: true
  num_threads: 6
  lambda_l1: 1.0
  lambda_l2: 1.0

params_bin:
  objective: binary
  metric: binary_logloss
  scale_pos_weight: 1.0

params_multi:
  objective: multiclassova
  num_class: 6
  metric: multi_logloss
  scale_pos_weight: 1.0

params_rank:
  objective: lambdarank
  metric: ndcg
  lambdarank_truncation_level: 8
  eval_at: [1,2,3,4,5]
